ss_file_pattern: toformat/{ss_file}.tsv
desired_build: '38'
chromosomes: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'MT']
remote_vcf_location: 'ftp://ftp.ensembl.org/pub/release-93/variation/vcf/homo_sapiens/'
vcf_local_path: vcf_refs/
parallel_step: 16
parallel_step_deeper: 16
